### PR TITLE
Windows Installer

### PR DESCRIPTION
**Pull request by c-geek**

### CODE REVIEW

**Comment by Insoleet** [comment]
What are the features provided by this installer ?

**Comment by c-geek** [comment]
It installs Sakia under C:\Program Files\Sakia, adds shortcuts for installation/uninstall in start menu, and proposes a Dekstop shortcut also.

And it displays licence acceptation before proceeding.

You can try it in a VM first.

**Comment by Insoleet** [comment]
Ok, seems great. Does the uninstall clears the cache ?

**Comment by c-geek** [comment]
You can do this on install phase:

```
[InstallDelete]
Type: filesandordirs; Name: "{userappdata}\sakia\cgeek\__cache__"
```

But as you can see, I cannot use wildcard to remove all the caches.

See http://www.jrsoftware.org/ishelp/index.php?topic=uninstalldeletesection

**Comment by Insoleet** [comment]
Oh ok. Well, can we add a checkbox to remove data when we uninstall ?

**Comment by c-geek** [comment]
I don't know, however this would only solve the problem for Windows users.

That's why I've personnaly chosen to [have an incremental database update script](https://github.com/duniter/duniter/blob/master/app/lib/dal/sqliteDAL/MetaDAL.js#L30-L42) on startup for Duniter, I will use it as much as I can.

**Comment by Insoleet** [comment]
Interesting method. I versioned my cache so I will probably have to do something like this someday.

For the checkbox, I was thinking about being able to clean data or not when uninstalling Sakia.

**Comment by c-geek** [comment]
This is probably the best way: a batch with checkbox option at the end of the installation.

You could also tune the batch to delete only `__cache__` or whatever.

Have fun!

**Comment by Insoleet** [comment]
Thanks !

**Pull request merged**
