### PR TITLE
READY:Test helpers : Message box, click yes vs enter

### PR DESCRIPTION
**Pull request by florck**
Instead of hitting enter, we click ont the yes button.

### CODE REVIEW

**Comment by Insoleet** [comment]
I have an idea : could it be possible to develop an helper which takes as a parameter the clicked button ?

Like : 
```
click_on_top_message_box(QMessageBox.Yes)
```

This way we could have a clean helper common to all the tests.

**Comment by florck** [comment]
Fact is that for the box where button is « Ok », I don’t know what we should click, since QMessageBox.Ok doesn’t exist...

**Comment by florck** [comment]
@Insoleet I'm still on it, got some good improvements alread! However, I find some surprizes ! For instance, one never enter, in test_connection_config in 64 and next steps since box is closed by the "enter" hit... 
So it will require so more investigation job!

**Comment by Insoleet** [comment]
I don't understand, what do you have on live 64 ?

**Comment by florck** [comment]
As explained, it is following of test line 64.

But indeed, my supposition was wrong. I have a discrepancy regarding the behavior depending on the way it is launched : with breakpoints or not.
With breakpoints, once window closed, it doesn't continue, whereas otherwise it continues...

**Comment by florck** [comment]
@Insoleet Je rebaserai quand la branche dev sera ok, à moins que tu veuilles résoudre le conflit.
Normalement c'est tout bon !

**Comment by Insoleet** [comment]
Thank you very much ! I sent you 50 UD for your contribution :) I hope you enjoyed going throught Sakia code !

**Pull request closed without merging**
